# See http://docs.openstack.org/developer/heat/template_guide/hot_spec.html

heat_template_version: 2015-10-15

description: Launch a Docker Registry Mirror

parameters:
   key_name:
      description: Name of an existing key pair to use for the instance
      label: Key Name
      type: string
      constraints:
         - custom_constraint: nova.keypair
   flavor:
      description: Small flavor (typically 1c/2g)
      label: Flavor ID
      type: string
   qserv_image_id:
      description: UUID of centos image for qserv (with docker)
      label: Image ID
      type: string
   network_name:
      description: Name of the network to connect to
      label: Network Name
      type: string
      constraints:
         - custom_constraint: neutron.network
   subnet_name:
      description: Name of the subnet to connect to
      label: Subnet Name
      type: string
      constraints:
         - custom_constraint: neutron.subnet
   public_network:
      description: Public network id
      type: string
   volume_id:
      description: Existing Volume ID to store cached docker images
      type: string   

resources:
## Docker Registry Mirror ##
   dr_instance:
      type: OS::Nova::Server
      properties:
         key_name: { get_param: key_name }
         flavor: { get_param: flavor }
         image: { get_param: qserv_image_id }
         networks:
            - port: { get_resource: dr_port }
         user_data: { get_file: cloud-config-dr.yaml }
         user_data_format: RAW
         name: docker-registry-mirror 

   dr_volume:
      type: OS::Cinder::VolumeAttachment
      properties:
         mountpoint: /dev/vdb
         volume_id: { get_param: volume_id }
         instance_uuid: { get_resource: dr_instance }
   dr_port:
      type: OS::Neutron::Port
      properties:
         network: { get_param: network_name }
         fixed_ips:
            - subnet_id: { get_param: subnet_name }

outputs:
    docker_registry_ip:
        description: Local docker-registry IP
        value: { get_attr: [ dr_instance, first_address ] }
# EOF
