# See http://docs.openstack.org/developer/heat/template_guide/hot_spec.html

heat_template_version: 2015-10-15

description: Worker template

parameters:
    key_name:
        type: string
    flavor_id:
        type: string
    image_id:
        type: string
    prefix:
        type: string
    network_name:
        type: string
    subnet_name:
        type: string
    mount_point:
        type: string
    volumes:
        type: comma_delimited_list
    index:
        type: number

resources:
    instance:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            flavor: { get_param: flavor_id }
            image: { get_param: image_id }
            networks:
                - port: { get_resource: port }
            user_data: { get_file: cloud-config.yaml }
            user_data_format: RAW
            name: 
                str_replace: 
                    template: $PREFIX-worker-$IDX
                    params: 
                        $PREFIX: { get_param: prefix }
                        $IDX: { get_param: index }
    port:
        type: OS::Neutron::Port
        properties:
            network: { get_param: network_name }
            fixed_ips:
                - subnet_id: { get_param: subnet_name }
    attachement:
        type: OS::Cinder::VolumeAttachment
        properties:
            mountpoint: { get_param: mount_point }
            volume_id: { get_param: [ volumes, {get_param: index } ] }
            instance_uuid: { get_resource: instance }

outputs:
    instance_ip:
        description: IP address of the deployed instance
        value: { get_attr: [ instance, first_address ] }
    port:
        value: { get_resource: port }
#EOF
