# default values are set for Galactica (LIMOS)
# keypair : qserv-qserv
# flavor #3 : m1.medium : 2c/4G/40G
# image : centos7-qserv (ce467a12-3851-41fa-a694-e007ee4a25c3)

# See http://docs.openstack.org/developer/heat/template_guide/hot_spec.html

heat_template_version: 2015-10-15

description: Worker template

parameters:
    key_name:
        type: string
    flavor_id:
        type: string
    image_id:
        type: string
    name:
        type: string
    network_name:
        type: string
    subnet_name:
        type: string
    mount_point:
        type: string
    volumes:
        type: comma_delimited_list
    index:
        type: number

resources:
    instance:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            flavor: { get_param: flavor_id }
            image: { get_param: image_id }
            name: { get_param: name }
            networks:
                - port: { get_resource: port }
    port:
        type: OS::Neutron::Port
        properties:
            network: { get_param: network_name }
            fixed_ips:
                - subnet_id: { get_param: subnet_name }
    attachement:
        type: OS::Cinder::VolumeAttachment
        properties:
            mountpoint: { get_param: mount_point }
            volume_id: { get_param: [ volumes, {get_param: index } ] }
            instance_uuid: { get_resource: instance }

